<a href="https://colab.research.google.com/github/shoaib646/AWS/blob/master/00_Pytroch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
print('Scalar: ', scalar)
print('scalar.ndim: ',scalar.ndim)
print(type(scalar.item()), scalar.item())

Scalar:  tensor(7)
scalar.ndim:  0
<class 'int'> 7


In [3]:
#vector
vector = torch.tensor([7,7])
print('Vector:', vector)
print('vector.shape: ',vector.shape)
print('vector.ndim: ',vector.ndim)

Vector: tensor([7, 7])
vector.shape:  torch.Size([2])
vector.ndim:  1


In [4]:
#Matrix

matrix = torch.tensor([[2,3], [1,4]])
print('matrix: ',matrix)
print('matrix.shape: ',matrix.shape)
print('matrix.ndim: ',matrix.ndim)

matrix:  tensor([[2, 3],
        [1, 4]])
matrix.shape:  torch.Size([2, 2])
matrix.ndim:  2


In [5]:
#TENSOR

TENSOR = torch.tensor([[1,2,3], [3,4,5], [6,7,8]])

In [6]:
TENSOR.ndim

2

In [7]:
TENSOR.shape

torch.Size([3, 3])

In [8]:
torch.randint(9, (3,3))

tensor([[4, 8, 2],
        [4, 0, 1],
        [4, 0, 7]])

In [9]:
torch.linspace(0,27, 5)

tensor([ 0.0000,  6.7500, 13.5000, 20.2500, 27.0000])

In [10]:
torch.manual_seed(20)
torch.rand(1,2, 2)

tensor([[[0.5615, 0.1774],
         [0.8147, 0.3295]]])

In [11]:
torch.Tensor([1,2])

tensor([1., 2.])

In [12]:
torch.zeros((2,10))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
torch.ones((2,10))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
torch.arange(0, 10,2) * 10

tensor([ 0, 20, 40, 60, 80])

In [15]:

a = torch.tensor([[1, 2,3], [4, 5,6]])
b = torch.tensor([[7,8], [9,10],[11,12]])

In [16]:
torch.mm(a,b)

tensor([[ 58,  64],
        [139, 154]])

In [17]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [18]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
x[0][:,1]

tensor([2, 5, 8])

In [20]:
x[0][:2,0]

tensor([1, 4])

In [21]:
%%time
x[0][0]

CPU times: user 68 µs, sys: 0 ns, total: 68 µs
Wall time: 72.7 µs


tensor([1, 2, 3])

In [22]:
%%time
x[0,0,:]

CPU times: user 103 µs, sys: 17 µs, total: 120 µs
Wall time: 251 µs


tensor([1, 2, 3])

In [23]:
%%time
x[:][0,2][2]

CPU times: user 91 µs, sys: 15 µs, total: 106 µs
Wall time: 109 µs


tensor(9)

In [24]:
%%time
x[0][2][2]

CPU times: user 70 µs, sys: 12 µs, total: 82 µs
Wall time: 85.6 µs


tensor(9)

In [25]:
import numpy as np

In [26]:

%%time
np.arange(1,10).reshape(1,3,3)[0][2][2]

CPU times: user 41 µs, sys: 7 µs, total: 48 µs
Wall time: 52.2 µs


9

In [27]:
## Large Language Model (LLMs) Transformers, Bert vagerax`x`x`

In [28]:
# created tensor
tensor = torch.arange(1,10).reshape(3,3)
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
# converted to numpy then again converted to tensor
torch.from_numpy(torch.Tensor.numpy(tensor))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
#reproducbility
torch.manuasl_seed(101)